#!/bin/sh

if [[ -z ${JIANMU_BOT_WEBHOOK_URL} ]]
then
    echo 'Error: JIANMU_BOT_WEBHOOK_URL is empty!'
    exit 1
fi

if [[ -z ${JIANMU_MSGTYPE} ]]
then
    echo 'Error: JIANMU_MSGTYPE is empty!'
    exit 1
fi

case ${JIANMU_MSGTYPE} in
  text)
    send_text
  ;;
  markdown)
    send_markdown
  ;;
  image)
    send_image
  ;;
  news)
    send_news
  ;;
  *)
    echo "Error: The value of JIANMU_MSGTYPE must be in (text|markdown|image|news)!"
    exit 1
  ;;
esac
